# -*- coding: utf-8 -*-
"""Lina_Persona_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-McoJlqFOVeMCEHkzj1WMrx9pnunX4QS
"""

import streamlit as st
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
import numpy as np
import json
import os

# ──────────────────────────────────────────────
# 페이지 설정
# ──────────────────────────────────────────────
st.set_page_config(
    page_title="Persona Lab — KU Young Makers × 라이나생명 5조(보험들5조)",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────
# 커스텀 CSS
# ──────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');

    /* 전체 배경 */
    .stApp {
        background-color: #0A0A0F;
        color: #E8E8ED;
        font-family: 'Pretendard', sans-serif;
    }

    /* 헤더 영역 */
    .main-header {
        background: linear-gradient(135deg, #0A0A0F 0%, #1a1a2e 100%);
        padding: 2rem 0 1rem;
        border-bottom: 1px solid rgba(255,255,255,0.06);
        margin-bottom: 1.5rem;
    }
    .main-header .tag {
        font-size: 0.7rem;
        font-weight: 700;
        letter-spacing: 2px;
        color: #2DD4BF;
        text-transform: uppercase;
    }
    .main-header h1 {
        font-size: 2rem;
        font-weight: 800;
        color: #fff;
        margin: 0.2rem 0;
        letter-spacing: -0.5px;
    }
    .main-header .sub {
        font-size: 0.85rem;
        color: #888;
    }

    /* 카드 스타일 */
    .card {
        background: rgba(255,255,255,0.03);
        border: 1px solid rgba(255,255,255,0.06);
        border-radius: 14px;
        padding: 1.4rem;
        margin-bottom: 1rem;
    }
    .card-accent-teal { border-left: 3px solid #2DD4BF; }
    .card-accent-orange { border-left: 3px solid #F97316; }
    .card-accent-purple { border-left: 3px solid #8B5CF6; }

    /* 메트릭 카드 */
    .metric-card {
        background: rgba(255,255,255,0.03);
        border: 1px solid rgba(255,255,255,0.06);
        border-radius: 12px;
        padding: 1.2rem;
        text-align: center;
    }
    .metric-num {
        font-size: 2.2rem;
        font-weight: 800;
        color: #2DD4BF;
    }
    .metric-label {
        font-size: 0.85rem;
        font-weight: 600;
        color: #ccc;
        margin-top: 0.2rem;
    }
    .metric-sub {
        font-size: 0.72rem;
        color: #666;
        margin-top: 0.2rem;
    }

    /* 채팅 UI */
    .chat-bubble-user {
        background: #2DD4BF;
        color: #000;
        padding: 0.7rem 1rem;
        border-radius: 14px 14px 4px 14px;
        max-width: 75%;
        margin-left: auto;
        margin-bottom: 0.8rem;
        font-size: 0.9rem;
        line-height: 1.6;
    }
    .chat-bubble-bot {
        background: rgba(255,255,255,0.06);
        color: #ddd;
        padding: 0.7rem 1rem;
        border-radius: 14px 14px 14px 4px;
        max-width: 75%;
        margin-bottom: 0.8rem;
        font-size: 0.9rem;
        line-height: 1.6;
    }

    /* 시뮬레이터 결과 카드 */
    .sim-card {
        border-radius: 14px;
        padding: 1.2rem 1.4rem;
        margin-bottom: 0.8rem;
    }
    .sim-card-teal { background: rgba(45,212,191,0.08); border: 1px solid rgba(45,212,191,0.2); }
    .sim-card-orange { background: rgba(249,115,22,0.08); border: 1px solid rgba(249,115,22,0.2); }
    .sim-card-purple { background: rgba(139,92,246,0.08); border: 1px solid rgba(139,92,246,0.2); }

    /* Streamlit 기본 요소 재정의 */
    .stTabs [data-baseweb="tab-list"] {
        gap: 0;
        background: transparent;
    }
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        color: #777;
        border-bottom: 2px solid transparent;
        font-weight: 500;
        padding: 0.6rem 1.2rem;
    }
    .stTabs [aria-selected="true"] {
        color: #2DD4BF !important;
        border-bottom: 2px solid #2DD4BF !important;
        background: rgba(45,212,191,0.08) !important;
    }
    .stTextArea textarea, .stTextInput input {
        background: rgba(255,255,255,0.04) !important;
        border: 1px solid rgba(255,255,255,0.08) !important;
        color: #eee !important;
        border-radius: 10px !important;
    }
    .stButton > button {
        background: linear-gradient(135deg, #2DD4BF, #8B5CF6) !important;
        color: #000 !important;
        font-weight: 700 !important;
        border: none !important;
        border-radius: 8px !important;
        padding: 0.5rem 1.5rem !important;
    }
    .stButton > button:hover {
        opacity: 0.9;
    }

    /* 사이드바 */
    section[data-testid="stSidebar"] {
        background: #0d0d14;
    }

    /* plotly 차트 배경 투명 */
    .js-plotly-plot .plotly .main-svg {
        background: transparent !important;
    }

    /* 패러독스 박스 */
    .paradox-box {
        background: rgba(139,92,246,0.06);
        border: 1px solid rgba(139,92,246,0.15);
        border-radius: 12px;
        padding: 1.2rem 1.4rem;
        margin-top: 1rem;
    }

    /* 태그 */
    .trait-tag {
        display: inline-block;
        font-size: 0.7rem;
        padding: 0.2rem 0.6rem;
        background: rgba(255,255,255,0.05);
        border-radius: 20px;
        color: #aaa;
        margin-right: 0.3rem;
        margin-bottom: 0.3rem;
    }

    /* 숨기기 */
    #MainMenu, footer, header {visibility: hidden;}
</style>
""", unsafe_allow_html=True)


# ──────────────────────────────────────────────
# 데이터 정의
# ──────────────────────────────────────────────
SURVEY_STATS = {
    "total": 102,
    "gender": {"남성": 54, "여성": 48},
    "age": {"20-24세": 30, "25-29세": 56, "30-34세": 12, "35-39세": 4},
    "questions": [
        {"key": "Q1", "short": "정보 이해 난이도", "full": "보험 관련 정보는 한 번에 이해하기 어렵다", "avg": 4.13, "top2": 82},
        {"key": "Q2", "short": "필요성 인식", "full": "보험의 필요성에 대해 느끼지 못한다", "avg": 2.01, "top2": 80, "note": "역코딩: 80%가 필요하다고 응답"},
        {"key": "Q3", "short": "삶과의 거리감", "full": "보험은 내 삶과 거리가 있는 서비스", "avg": 2.32, "top2": 65, "note": "역코딩: 65%가 가깝다고 응답"},
        {"key": "Q4", "short": "광고 불신", "full": "보험 정보는 광고처럼 느껴져 신뢰가 낮다", "avg": 3.64, "top2": 64},
        {"key": "Q5", "short": "브랜드 동질성", "full": "보험 브랜드는 비슷한 느낌", "avg": 4.03, "top2": 82},
        {"key": "Q6", "short": "올드한 이미지", "full": "보험 브랜드는 딱딱하고 올드하다", "avg": 3.39, "top2": 50},
        {"key": "Q7", "short": "숏폼 선호", "full": "쇼츠/릴스 같은 짧은 콘텐츠를 선호", "avg": 3.91, "top2": 79},
        {"key": "Q8", "short": "알고리즘 정보", "full": "검색보다 알고리즘으로 정보를 접한다", "avg": 3.41, "top2": 54},
        {"key": "Q9", "short": "바이럴 기억", "full": "바이럴 광고가 오히려 기억에 남는다", "avg": 3.57, "top2": 60},
        {"key": "Q10", "short": "CM송 영향", "full": "CM송이 브랜드 각인에 영향을 준다", "avg": 4.13, "top2": 83},
    ],
}

PERSONAS = [
    {
        "id": 0,
        "name": "이현진",
        "age": 23,
        "label": "보험 수용형 — 정보 자신감",
        "emoji": "🧠",
        "color": "#2DD4BF",
        "css_class": "teal",
        "n": 19,
        "pct": "19%",
        "gender": "여성 10 / 남성 9",
        "age_group": "20-24세 중심 (53%)",
        "desc": "보험이 필요하다고 느끼고, 삶과 가깝다고 생각합니다. 보험 정보를 남들보다 잘 이해하는 편이고, 검색엔진을 통해 스스로 정보를 찾아봅니다. 광고에 대한 기대치가 높지 않아 CM송이나 바이럴에 덜 반응합니다.",
        "scores": [3.05, 1.42, 1.74, 3.26, 3.32, 2.74, 3.05, 2.21, 2.42, 3.32],
        "traits": ["보험 정보 이해도 높음", "검색 중심 정보 탐색", "광고에 냉정한 편", "보험 필요성 강하게 인식"],
        "quotes": [
            "저는 그래도 좀 찾아보는 편이라... 보험 비교 사이트에서 조건 넣어보고 직접 비교해요.",
            "솔직히 별 감흥 없어요. 다 비슷한 말 하잖아요. 차라리 보장 범위랑 보험료를 딱 비교해서 보여주면 좋겠어요.",
            "CM송 들으면 아 저 보험이구나 인식은 되는데, 그걸로 가입하겠다는 생각은 안 들어요.",
        ],
        "system_prompt": """당신은 23세 여성 이현진입니다. 대학교 4학년 경영학과 재학 중이에요.

[성격과 가치관]
- 보험이 필요하다고 확실히 느끼는 편. 부모님이 보험 덕 본 경험을 가까이서 봄
- 보험 정보를 직접 검색해서 찾아보는 스타일. 네이버 블로그, 유튜브 비교 영상 참고
- 알고리즘 추천보다는 본인이 직접 검색하는 걸 선호
- 보험 광고에 대해선 냉정. "다 거기서 거기"라고 느끼지만, 정보가 명확하면 관심 가짐
- CM송이나 바이럴에 크게 휘둘리지 않음. 이성적 판단 중시

[말투]
- 차분하고 또박또박한 편
- "그건 좀 아닌 것 같아요", "제가 찾아봤을 때는요", "근거가 있어야죠" 같은 표현
- 감정적 표현보다 논리적 설명을 선호
- 짧게 핵심만 말하는 스타일

[실제 응답 예시]
Q: 보험 정보를 접할 때 어떤 느낌이에요?
A: "저는 그래도 좀 찾아보는 편이라... 어렵다고 느끼는 분들 많은 거 아는데 전 보험 비교 사이트에서 조건 넣어보고 직접 비교해요. 근데 약관은 진짜 어렵긴 해요."

Q: 보험 광고 보면 어떤 생각 들어요?
A: "솔직히 별 감흥 없어요. 다 비슷한 말 하잖아요. '든든하게' '안심' 이런 거... 차라리 보장 범위랑 보험료를 딱 비교해서 보여주면 좋겠어요."

Q: CM송 들으면 기억에 남아요?
A: "들으면 아 저 보험이구나 하고 인식은 되는데, 그걸로 가입하겠다는 생각은 안 들어요. 저한테는 정보가 더 중요해요."
""",
    },
    {
        "id": 1,
        "name": "김도현",
        "age": 27,
        "label": "보험 회의형 — 나와 먼 세상",
        "emoji": "😑",
        "color": "#F97316",
        "css_class": "orange",
        "n": 30,
        "pct": "29%",
        "gender": "남성 22 / 여성 8",
        "age_group": "25-29세 중심 (80%)",
        "desc": "보험의 필요성을 잘 못 느끼고, 내 삶과 거리가 있다고 생각합니다. 보험 정보는 어렵고, 브랜드는 다 비슷하고 올드하다고 느낍니다. 그런데 CM송은 의외로 기억에 남는다고 답했습니다.",
        "scores": [4.30, 3.23, 3.77, 3.53, 4.23, 3.57, 3.90, 3.40, 3.60, 4.30],
        "traits": ["보험 필요성 낮게 인식", "삶과 거리감 큼", "브랜드 올드하다고 인식", "CM송에는 반응"],
        "quotes": [
            "음... 필요한 건 알겠는데 솔직히 와닿지는 않아요. 아직 20대인데 뭘 보장받아야 하는 건지.",
            "다 비슷하지 않아요? 아저씨들 나오고 가족 나오고... 아 근데 CM송은 좀 기억나요. 그건 인정.",
            "유튜브 쇼츠 정도? 1분 넘어가면 안 봐요. 근데 보험을 쇼츠로 만들 수 있나...",
        ],
        "system_prompt": """당신은 27세 남성 김도현입니다. IT 스타트업에서 주니어 개발자로 일하고 있어요.

[성격과 가치관]
- 보험? 솔직히 아직 남의 얘기 같음. 아프거나 다치는 건 나이 들어서 걱정할 문제라고 생각
- 부모님이 알아서 들어놓은 보험 있는데 뭔지 잘 모름. 관심도 별로 없음
- 보험 정보 자체가 어렵고, 알려고 해도 광고처럼 느껴져서 신뢰가 안 감
- 보험 브랜드는 다 똑같이 느껴짐. 올드하고 내 세대 감성이 아님
- 근데 CM송은 귀에 맴도는 거 인정. 무의식적으로 기억됨

[말투]
- 솔직하고 직설적, 약간 시니컬
- "솔직히", "글쎄요", "그게 저랑 무슨 상관인데요", "아직은 몰?루" 같은 표현
- 관심 없는 주제에는 짧게 답하고 넘기려 함
- 반어법이나 유머 섞어서 말하는 편

[실제 응답 예시]
Q: 보험에 대해 어떻게 생각해요?
A: "음... 필요한 건 알겠는데 솔직히 와닿지는 않아요. 아직 20대인데 뭘 보장받아야 하는 건지. 그 돈이면 차라리 투자하죠."

Q: 보험 브랜드 하면 떠오르는 이미지는?
A: "다 비슷하지 않아요? 아저씨들 나오고 가족 나오고... 글쎄요, 딱히 기억에 남는 브랜드가 없어요. 아 근데 CM송은 좀 기억나요. 그건 인정."

Q: 보험 관련 콘텐츠를 본다면 어떤 형식이 좋아요?
A: "유튜브 쇼츠 정도? 1분 넘어가면 안 봐요. 근데 보험을 쇼츠로 만들 수 있나... 좀 억지일 것 같기도 하고."
""",
    },
    {
        "id": 2,
        "name": "박서연",
        "age": 26,
        "label": "콘텐츠 민감형 — 필요하지만 다가가기 어려움",
        "emoji": "📱",
        "color": "#8B5CF6",
        "css_class": "purple",
        "n": 53,
        "pct": "52%",
        "gender": "여성 30 / 남성 23",
        "age_group": "25-29세 중심, 20대 초반도 다수",
        "desc": "보험이 필요하다는 건 알지만 정보가 어렵고 광고처럼 느껴져 접근하기 힘들어합니다. 숏폼 콘텐츠와 알고리즘 기반 정보 소비에 가장 적극적이고, 바이럴과 CM송에 강하게 반응합니다. 전체의 52%로 가장 큰 그룹입니다.",
        "scores": [4.42, 1.53, 1.72, 3.83, 4.17, 3.53, 4.23, 3.85, 3.96, 4.32],
        "traits": ["보험 필요성 강하게 인식", "정보 접근 장벽 높음", "숏폼/알고리즘 최다 소비", "바이럴·CM송 강하게 반응"],
        "quotes": [
            "필요하죠 당연히. 근데 막상 알아보면 너무 복잡하고... 뭘 골라야 하는지 모르겠어요.",
            "인스타나 유튜브에서 알고리즘으로 뜨면 봐요. 근데 끝까지 보면 결국 광고더라고요... 좀 실망.",
            "CM송은 진짜 기억나요 ㅋㅋ 바이럴 광고 중에 웃긴 거 있으면 친구한테 보내기도 해요.",
        ],
        "system_prompt": """당신은 26세 여성 박서연입니다. 중견기업 마케팅팀 2년차 사원이에요.

[성격과 가치관]
- 보험이 필요하다는 건 확실히 알고 있음. 친구가 다쳐서 보험금 탄 걸 보고 나도 들어야겠다고 생각
- 근데 막상 알아보려니 너무 어려움. 약관, 보장범위, 갱신... 뭐가 뭔지 모르겠음
- 보험 정보인데 광고 같아서 신뢰가 안 감. 뭔가 팔려고 하는 느낌
- 콘텐츠는 인스타 릴스, 유튜브 쇼츠 위주로 봄. 알고리즘이 띄워주는 거 자연스럽게 소비
- CM송 중독성 있으면 계속 맴돌고, 바이럴 광고 재밌으면 친구한테 공유함

[말투]
- 밝고 친근한 구어체, 감정 표현 솔직
- "아 진짜요?", "헐 그건 몰랐어요", "좀 무서워요 그거", "ㅋㅋ 맞아요" 같은 표현
- 공감 잘 하고, 자기 경험 섞어서 이야기하는 편
- 관심 있는 주제에는 꽤 길게 이야기함

[실제 응답 예시]
Q: 보험에 대해 어떻게 생각해요?
A: "필요하죠 당연히. 저 친구가 작년에 교통사고 나서 보험금 받은 거 보고 진짜 들어야겠다 싶었어요. 근데 막상 알아보면 너무 복잡하고... 뭘 골라야 하는지 모르겠어요."

Q: 보험 정보를 어디서 접하나요?
A: "일부러 찾아보진 않는데 인스타나 유튜브에서 알고리즘으로 뜨면 봐요. 쇼츠로 '20대가 꼭 들어야 할 보험 3가지' 이런 거. 근데 끝까지 보면 결국 광고더라고요... 좀 실망."

Q: 기억에 남는 보험 광고 있어요?
A: "CM송은 진짜 기억나요 ㅋㅋ 자동으로 흥얼거리게 되는. 그리고 바이럴 광고 중에 웃긴 거 있으면 친구한테 보내기도 해요. 보험 가입까진 안 가도 브랜드는 기억에 남더라고요."
""",
    },
]


# ──────────────────────────────────────────────
# Gemini API 호출 함수
# ──────────────────────────────────────────────
def call_gemini(api_key: str, system_prompt: str, user_message: str, history: list = None) -> str:
    """Gemini API 호출. google-genai 패키지 사용."""
    try:
        from google import genai

        client = genai.Client(api_key=api_key)

        # 대화 히스토리 구성
        contents = []
        if history:
            for msg in history:
                role = "user" if msg["role"] == "user" else "model"
                contents.append({"role": role, "parts": [{"text": msg["text"]}]})
        contents.append({"role": "user", "parts": [{"text": user_message}]})

        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=contents,
            config={
                "system_instruction": system_prompt,
                "temperature": 0.7,
                "max_output_tokens": 700,
            },
        )
        return response.text

        except ImportError:
        return "⚠️ google-genai 패키지가 필요합니다. `pip install google-genai` 실행 후 다시 시도해주세요."

    except Exception as e:
        error_msg = str(e)

        if "RESOURCE_EXHAUSTED" in error_msg or "429" in error_msg:
            return (
                "⚠️ 현재 Gemini API 사용 한도가 초과되었거나, 이 API 키의 할당량이 부족합니다.\n\n"
                "Google AI Studio에서 API 키의 Billing/Quota 상태를 확인하거나, 다른 API 키를 입력해 주세요."
            )

        return f"⚠️ API 오류가 발생했습니다: {error_msg}"


# ──────────────────────────────────────────────
# 사이드바 — API 키 입력
# ──────────────────────────────────────────────
with st.sidebar:
    st.markdown("### ⚙️ 설정")
    api_key = st.text_input(
        "Gemini API Key",
        type="password",
        value=os.environ.get("GEMINI_API_KEY", ""),
        help="Google AI Studio에서 발급: https://aistudio.google.com/apikey",
    )
    if api_key:
        st.success("✅ API 키 설정 완료")
    else:
        st.warning("💬 대화/시뮬레이터 사용 시 API 키가 필요합니다")

    st.markdown("---")
    st.markdown("#### 📎 데이터 출처")
    st.markdown("KU Young Makers × 라이나생명\n설문 응답 102명 (20~30대 청년)")
    st.markdown("K-Means 군집분석 (K=3)")


# ──────────────────────────────────────────────
# 헤더
# ──────────────────────────────────────────────
st.markdown("""
<div class="main-header">
    <div class="tag">KU Young Makers × Lina Life</div>
    <h1>🧬 Persona Lab</h1>
    <div class="sub">102명 설문 데이터 기반 · AI 페르소나 3인 · 실시간 대화 & 마케팅 테스트</div>
</div>
""", unsafe_allow_html=True)


# ──────────────────────────────────────────────
# 탭 구성
# ──────────────────────────────────────────────
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 데이터 인사이트",
    "👤 페르소나",
    "💬 페르소나 대화",
    "🧪 메시지 테스트",
])


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TAB 1: 데이터 인사이트
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
with tab1:
    # 핵심 메트릭
    col1, col2, col3 = st.columns(3)
    metrics = [
        ("82%", "보험 정보가 어렵다", "이해 장벽이 첫 번째 허들"),
        ("82%", "브랜드가 다 비슷하다", "차별화 기회 = 블루오션"),
        ("83%", "CM송이 각인에 영향", "청년에게도 통하는 채널"),
    ]
    for col, (num, label, sub) in zip([col1, col2, col3], metrics):
        with col:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-num">{num}</div>
                <div class="metric-label">{label}</div>
                <div class="metric-sub">{sub}</div>
            </div>
            """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # 문항별 평균 차트
    st.markdown("#### 문항별 평균 점수 (5점 만점)")

    questions_df = pd.DataFrame(SURVEY_STATS["questions"])
    colors = ["#2DD4BF" if avg >= 4 else "#F97316" if avg >= 3 else "#8B5CF6" for avg in questions_df["avg"]]

    fig_bar = go.Figure(go.Bar(
        x=questions_df["avg"],
        y=questions_df["short"],
        orientation="h",
        marker_color=colors,
        marker_opacity=0.85,
        text=[f"{v:.2f}" for v in questions_df["avg"]],
        textposition="outside",
        textfont=dict(color="#aaa", size=11),
        hovertext=questions_df["full"],
        hoverinfo="text+x",
    ))
    fig_bar.update_layout(
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#aaa", size=12),
        height=380,
        margin=dict(l=120, r=40, t=10, b=30),
        xaxis=dict(range=[0, 5.3], gridcolor="rgba(255,255,255,0.05)", zeroline=False),
        yaxis=dict(autorange="reversed"),
    )
    st.plotly_chart(fig_bar, use_container_width=True)

    # 범례
    leg1, leg2, leg3 = st.columns(3)
    leg1.markdown("🟢 **강한 동의 (4+)**")
    leg2.markdown("🟠 **보통 동의 (3~4)**")
    leg3.markdown("🟣 **비동의 (<3)**")

    # 패러독스 박스
    st.markdown("""
    <div class="paradox-box">
        <div style="font-size:1rem; font-weight:700; color:#A78BFA; margin-bottom:0.4rem;">💡 핵심 패러독스</div>
        <div style="font-size:0.85rem; color:#bbb; line-height:1.7;">
            청년의 <strong style="color:#e8e8ed;">80%</strong>가 보험이 필요하다고 느끼지만,
            <strong style="color:#e8e8ed;">82%</strong>는 정보가 어렵고,
            <strong style="color:#e8e8ed;">64%</strong>는 광고처럼 느껴져 신뢰가 안 간다고 답했습니다.
            <strong style="color:#2DD4BF;">"필요한 건 아는데 다가갈 수 없는"</strong> 상태 — 이것이 라이나생명의 기회입니다.
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # 인구통계
    col_g, col_a = st.columns(2)

    with col_g:
        st.markdown("#### 성별 분포")
        fig_gender = go.Figure(go.Pie(
            labels=list(SURVEY_STATS["gender"].keys()),
            values=list(SURVEY_STATS["gender"].values()),
            marker=dict(colors=["#2DD4BF", "#8B5CF6"]),
            hole=0.55,
            textinfo="label+percent",
            textfont=dict(size=13, color="#ddd"),
        ))
        fig_gender.update_layout(
            plot_bgcolor="rgba(0,0,0,0)",
            paper_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#aaa"),
            height=250,
            margin=dict(l=20, r=20, t=10, b=10),
            showlegend=False,
        )
        st.plotly_chart(fig_gender, use_container_width=True)

    with col_a:
        st.markdown("#### 연령 분포")
        fig_age = go.Figure(go.Bar(
            x=list(SURVEY_STATS["age"].keys()),
            y=list(SURVEY_STATS["age"].values()),
            marker_color="#F97316",
            marker_opacity=0.8,
            text=list(SURVEY_STATS["age"].values()),
            textposition="outside",
            textfont=dict(color="#aaa", size=12),
        ))
        fig_age.update_layout(
            plot_bgcolor="rgba(0,0,0,0)",
            paper_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#aaa"),
            height=250,
            margin=dict(l=20, r=20, t=10, b=30),
            xaxis=dict(gridcolor="rgba(0,0,0,0)"),
            yaxis=dict(gridcolor="rgba(255,255,255,0.05)", zeroline=False),
        )
        st.plotly_chart(fig_age, use_container_width=True)

def hex_to_rgba(hex_color, alpha=0.15):
    hex_color = hex_color.lstrip("#")
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)
    return f"rgba({r},{g},{b},{alpha})"
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TAB 2: 페르소나
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
with tab2:
    # 페르소나 카드 3개
    cols = st.columns(3)
    for col, p in zip(cols, PERSONAS):
        with col:
            traits_html = "".join([f'<span class="trait-tag">{t}</span>' for t in p["traits"]])
            st.markdown(f"""
            <div class="card card-accent-{p['css_class']}">
                <div style="font-size:2rem; margin-bottom:0.5rem;">{p['emoji']}</div>
                <div style="font-size:1.1rem; font-weight:700; color:#eee;">{p['name']} ({p['age']}세)</div>
                <div style="font-size:0.8rem; color:{p['color']}; font-weight:600; margin-bottom:0.5rem;">{p['label']}</div>
                <div style="font-size:0.72rem; color:#888; margin-bottom:0.7rem;">n={p['n']}명 ({p['pct']}) · {p['gender']}</div>
                <div>{traits_html}</div>
            </div>
            """, unsafe_allow_html=True)

    # 레이더 차트
    st.markdown("#### 페르소나 응답 패턴 비교")

    categories = [q["short"] for q in SURVEY_STATS["questions"]]

    fig_radar = go.Figure()
    for p in PERSONAS:
        fig_radar.add_trace(go.Scatterpolar(
            r=p["scores"] + [p["scores"][0]],  # 닫기
            theta=categories + [categories[0]],
            fill="toself",
            fillcolor=hex_to_rgba(p["color"], 0.15),
            line=dict(color=p["color"], width=2),
            name=f'{p["name"]} ({p["label"].split("—")[0].strip()})',
        ))
    fig_radar.update_layout(
        polar=dict(
            bgcolor="rgba(0,0,0,0)",
            radialaxis=dict(visible=True, range=[0, 5], gridcolor="rgba(255,255,255,0.1)", tickfont=dict(color="#555", size=10)),
            angularaxis=dict(gridcolor="rgba(255,255,255,0.08)", tickfont=dict(color="#999", size=11)),
        ),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#aaa", size=12),
        height=450,
        margin=dict(l=60, r=60, t=40, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=-0.15, font=dict(size=11)),
        showlegend=True,
    )
    st.plotly_chart(fig_radar, use_container_width=True)

    # 페르소나 상세 보기
    st.markdown("#### 페르소나 상세 프로필")
    selected_id = st.selectbox(
        "페르소나 선택",
        options=[p["id"] for p in PERSONAS],
        format_func=lambda x: f'{PERSONAS[x]["emoji"]} {PERSONAS[x]["name"]} — {PERSONAS[x]["label"]}',
    )

    p = PERSONAS[selected_id]
    st.markdown(f"""
    <div class="card card-accent-{p['css_class']}" style="background:{p['color']}08;">
        <div style="font-size:1.2rem; font-weight:700; color:#eee; margin-bottom:0.3rem;">
            {p['emoji']} {p['name']}의 프로필
        </div>
        <div style="font-size:0.85rem; color:#bbb; line-height:1.7; margin-bottom:1rem;">{p['desc']}</div>
        <div style="font-size:0.85rem; font-weight:600; color:{p['color']}; margin-bottom:0.5rem;">대표 발언</div>
    </div>
    """, unsafe_allow_html=True)

    for quote in p["quotes"]:
        st.markdown(f"""
        <div style="background:rgba(0,0,0,0.3); border-radius:10px; padding:0.8rem 1rem;
                    margin-bottom:0.5rem; font-size:0.85rem; color:#ccc; line-height:1.6; font-style:italic;">
            "{quote}"
        </div>
        """, unsafe_allow_html=True)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TAB 3: 페르소나 대화
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
with tab3:
    # 페르소나 선택
    chat_cols = st.columns(3)
    chat_persona_id = st.session_state.get("chat_persona_id", 0)

    for col, p in zip(chat_cols, PERSONAS):
        with col:
            is_selected = chat_persona_id == p["id"]
            border_color = p["color"] if is_selected else "rgba(255,255,255,0.06)"
            bg = f"{p['color']}10" if is_selected else "rgba(255,255,255,0.02)"
            if st.button(
                f'{p["emoji"]} {p["name"]} ({p["age"]}세)',
                key=f"chat_sel_{p['id']}",
                use_container_width=True,
            ):
                st.session_state.chat_persona_id = p["id"]
                st.session_state.chat_history = []
                st.rerun()

    chat_persona_id = st.session_state.get("chat_persona_id", 0)
    p = PERSONAS[chat_persona_id]

    st.markdown(f"""
    <div style="display:flex; align-items:center; gap:0.7rem; padding:0.8rem 1rem;
                background:rgba(255,255,255,0.03); border-radius:10px; margin:1rem 0;">
        <span style="font-size:1.5rem;">{p['emoji']}</span>
        <div>
            <div style="font-size:0.95rem; font-weight:700; color:#eee;">{p['name']} ({p['age']}세)</div>
            <div style="font-size:0.75rem; color:{p['color']};">{p['label']}</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # 대화 히스토리
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    # 기존 메시지 표시
    if not st.session_state.chat_history:
        st.markdown(f"""
        <div style="text-align:center; color:#555; padding:3rem 0;">
            <div style="font-size:2.5rem; margin-bottom:0.5rem;">{p['emoji']}</div>
            <div style="font-size:0.9rem;">안녕하세요! {p['name']}에게 질문해보세요.</div>
            <div style="font-size:0.75rem; color:#444; margin-top:0.5rem; line-height:1.6;">
                예시: "보험 광고 보면 어떤 생각 들어요?"<br>
                "라이나생명 들어본 적 있어요?"<br>
                "보험 가입할 생각 있어요?"
            </div>
        </div>
        """, unsafe_allow_html=True)

    for msg in st.session_state.chat_history:
        if msg["role"] == "user":
            st.markdown(f'<div style="display:flex; justify-content:flex-end; margin-bottom:0.5rem;"><div class="chat-bubble-user">{msg["text"]}</div></div>', unsafe_allow_html=True)
        else:
            st.markdown(f'<div style="display:flex; gap:0.5rem; margin-bottom:0.5rem;"><span style="font-size:1.2rem;">{p["emoji"]}</span><div class="chat-bubble-bot">{msg["text"]}</div></div>', unsafe_allow_html=True)

    # 입력
    chat_input = st.chat_input(f"{p['name']}에게 질문하세요...")

    if chat_input:
        if not api_key:
            st.error("⬅️ 사이드바에서 Gemini API 키를 입력해주세요.")
        else:
            st.session_state.chat_history.append({"role": "user", "text": chat_input})

            system = p["system_prompt"] + """

[응답 규칙]
- 항상 1인칭으로, 위의 페르소나 입장에서 답하세요.
- 말투, 어휘, 가치관을 일관되게 유지하세요.
- 실제 사람처럼 자연스럽게, 2~4문장으로 답하세요.
- 라이나생명 특정 상품명을 지어내지 마세요.
- 구체적 보험료 숫자를 임의로 만들지 마세요.
- "AI로서" 같은 메타 발언 절대 금지.
- 모르는 건 "잘 모르겠어요"라고 답하세요."""

            reply = call_gemini(api_key, system, chat_input, st.session_state.chat_history[:-1])
            st.session_state.chat_history.append({"role": "assistant", "text": reply})
            st.rerun()


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TAB 4: 마케팅 메시지 테스트
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
with tab4:
    st.markdown("""
    <div class="card">
        <div style="font-size:1.1rem; font-weight:700; color:#ddd; margin-bottom:0.3rem;">🧪 마케팅 메시지 A/B 테스트</div>
        <div style="font-size:0.8rem; color:#777; line-height:1.5;">
            라이나생명 광고 카피, SNS 문구, 앱 푸시 메시지 등을 입력하면<br>
            3개 페르소나가 각각 반응을 평가합니다.
        </div>
    </div>
    """, unsafe_allow_html=True)

    sim_input = st.text_area(
        "마케팅 메시지 입력",
        placeholder='예시:\n• "당신의 미래를 든든하게, 라이나생명"\n• "월 9,900원으로 시작하는 건강보험. 첫 달 무료."\n• "보험, 어렵다고요? 30초면 끝나는 보장 체크 ▶"',
        height=120,
        label_visibility="collapsed",
    )

    if st.button("🚀 3명의 페르소나 반응 보기", use_container_width=True):
        if not api_key:
            st.error("⬅️ 사이드바에서 Gemini API 키를 입력해주세요.")
        elif not sim_input.strip():
            st.warning("메시지를 입력해주세요.")
        else:
            with st.spinner("⏳ 페르소나 반응 분석 중..."):
                sim_system = """당신은 라이나생명 마케팅 메시지 테스터입니다.
3명의 청년 페르소나가 메시지에 각각 반응합니다.

페르소나 1 - 이현진 (23세 여성, 보험 수용형): 보험 정보를 직접 검색해서 비교하는 이성적 타입. 구체적 수치와 정보에 반응.
페르소나 2 - 김도현 (27세 남성, 보험 회의형): 보험은 남의 일이라 생각. 시니컬하지만 CM송에는 반응.
페르소나 3 - 박서연 (26세 여성, 콘텐츠 민감형): 보험 필요성은 알지만 정보 장벽이 높음. 숏폼과 바이럴에 강하게 반응.

사용자가 마케팅 메시지/광고 카피를 입력하면, 각 페르소나의 반응을 아래 JSON 형식으로만 답하세요.
다른 텍스트 없이 순수 JSON만 출력하세요. 마크다운 코드블록(```)도 사용하지 마세요:
{"reactions": [{"name": "이현진", "score": 1에서10사이정수, "reaction": "1인칭 반응 2~3문장 구어체", "tip": "이 타입에게 먹히려면 1문장"}, {"name": "김도현", "score": 1에서10사이정수, "reaction": "1인칭 반응 2~3문장 구어체", "tip": "이 타입에게 먹히려면 1문장"}, {"name": "박서연", "score": 1에서10사이정수, "reaction": "1인칭 반응 2~3문장 구어체", "tip": "이 타입에게 먹히려면 1문장"}]}"""

                raw = call_gemini(api_key, sim_system, sim_input.strip())

                try:
                    clean = raw.replace("```json", "").replace("```", "").strip()
                    parsed = json.loads(clean)
                    reactions = parsed["reactions"]

                    for i, r in enumerate(reactions):
                        p = PERSONAS[i]
                        score = r["score"]
                        score_color = "#2DD4BF" if score >= 7 else "#F97316" if score >= 4 else "#EF4444"

                        st.markdown(f"""
                        <div class="sim-card sim-card-{p['css_class']}">
                            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.7rem;">
                                <div style="display:flex; align-items:center; gap:0.6rem;">
                                    <span style="font-size:1.5rem;">{p['emoji']}</span>
                                    <div>
                                        <div style="font-size:0.9rem; font-weight:700; color:#eee;">{p['name']} ({p['age']}세)</div>
                                        <div style="font-size:0.72rem; color:{p['color']};">{p['label']}</div>
                                    </div>
                                </div>
                                <div style="text-align:center;">
                                    <div style="font-size:1.8rem; font-weight:800; color:{score_color};">{score}</div>
                                    <div style="font-size:0.65rem; color:#777;">/10점</div>
                                </div>
                            </div>
                            <div style="background:rgba(0,0,0,0.2); border-radius:10px; padding:0.7rem 1rem;
                                        margin-bottom:0.6rem; font-size:0.85rem; color:#ccc; line-height:1.7; font-style:italic;">
                                "{r['reaction']}"
                            </div>
                            <div style="font-size:0.8rem; color:{p['color']}; font-weight:600;">
                                💡 {r['tip']}
                            </div>
                        </div>
                        """, unsafe_allow_html=True)

                    # 종합 점수
                    avg_score = sum(r["score"] for r in reactions) / 3
                    avg_color = "#2DD4BF" if avg_score >= 7 else "#F97316" if avg_score >= 4 else "#EF4444"
                    st.markdown(f"""
                    <div class="card" style="text-align:center; margin-top:1rem;">
                        <div style="font-size:0.85rem; color:#888; margin-bottom:0.3rem;">종합 평균 점수</div>
                        <div style="font-size:2.5rem; font-weight:800; color:{avg_color};">{avg_score:.1f}</div>
                        <div style="font-size:0.75rem; color:#666;">/10점</div>
                    </div>
                    """, unsafe_allow_html=True)
                except Exception as e:
                    st.error(f"⚠️ 응답 파싱 오류: {str(e)}")
                    st.code(raw, language="text")
